import { createTimeISOString } from '@/utils/createTime';
import type { MigrateUpArgs } from '@payloadcms/db-postgres';
import path from 'path';

export async function up({ payload }: MigrateUpArgs): Promise<void> {
  await payload.create({
    collection: 'users',
    data: {
      name: 'Admin',
      email: 'admin@ans-ns.edu.pl',
      password: 'demo',
      roles: ['admin', 'user'],
      _verified: true,
    },
  });

  await payload.create({
    collection: 'universities',
    data: {
      name: 'Akademia Nauk Stosowanych',
      deanearyAddress: {
        street: 'Staszica',
        city: 'Nowy Sącz',
        zipCode: '33-300',
        buildingNumber: '1',
        country: 'Polska',
      },
      contact: {
        email: 'sog@ans-ns.edu.pl',
        phoneNumbers: [
          { phoneNumber: '+48 18 547 56 02' },
          { phoneNumber: '+48 18 547 56 03' },
        ],
      },
    },
  });

  const classroom = await payload.create({
    collection: 'classrooms',
    data: {
      floorNumber: 1,
      roomNumber: 9,
    },
  });

  const faculty = await payload.create({
    collection: 'faculties',
    data: {
      name: 'Wydział Inżynieryjny',
      classrooms: [classroom.id],
      address: {
        buildingNumber: '1A',
        city: 'Nowy Sącz',
        country: 'Polska',
        street: 'Zamenhofa',
        zipCode: '33-300',
      },
      contact: {
        email: 'wi@ans-ns.edu.pl',
        phoneNumbers: [
          { phoneNumber: '+48 18 547 29 08' },
          { phoneNumber: '+48 18 547 29 07' },
        ],
      },
    },
  });

  const lecturer = await payload.create({
    collection: 'lecturers',
    data: {
      firstName: 'Jan',
      middleName: 'Kazimierz',
      familyName: 'Nowak',
      academicTitles: ['BSc', 'prof'],
      address: {
        city: 'Nowy Sącz',
        street: 'Kwiatowa',
        zipCode: '33-300',
      },
      email: 'jankazimierz@ans-ns.edu.pl',
      phoneNumber: '+48 123 456 789',
    },
  });

  const schedule = await payload.create({
    collection: 'schedules',
    data: {
      weekAfullTimeSchedule: {
        monday: [
          {
            name: 'Grafika i komunikacja człowiek-komputer',
            form: 'project',
            startTime: createTimeISOString({ hours: 10, minutes: 10 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Programowanie zaawansowane',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 11, minutes: 45 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 3,
            lecturer: lecturer.id,
          },
          {
            name: 'Oprogramowanie CMS (Joomla)*',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 14, minutes: 15 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 3,
            lecturer: lecturer.id,
          },
        ],
        tuesday: [
          {
            name: 'Programowanie urządzeń mobilnych',
            form: 'project',
            startTime: createTimeISOString({ hours: 15, minutes: 25 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Systemy operacyjne',
            form: 'project',
            startTime: createTimeISOString({ hours: 17, minutes: 0 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Technologia sieciowa',
            form: 'lab',
            startTime: createTimeISOString({ hours: 18, minutes: 35 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
        ],
        wednesday: [
          {
            name: 'Język angielski',
            form: 'language',
            startTime: createTimeISOString({ hours: 9, minutes: 10 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
        ],
        thursday: [
          {
            name: 'Systemy operacyjne',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 9, minutes: 35 }),
            classroom: classroom.id,
            isOnline: true,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Systemy operacyjne',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 11, minutes: 15 }),
            classroom: classroom.id,
            isOnline: true,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Programowanie zaawansowane',
            form: 'project',
            startTime: createTimeISOString({ hours: 15, minutes: 25 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 3,
            lecturer: lecturer.id,
          },
          {
            name: 'Programowanie aplikacji WEB',
            form: 'project',
            startTime: createTimeISOString({ hours: 17, minutes: 50 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
        ],
        friday: [
          {
            name: 'Programowanie urządzeń mobilnych',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 8, minutes: 0 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 3,
            lecturer: lecturer.id,
          },
          {
            name: 'Technologia sieciowa',
            form: 'lab',
            startTime: createTimeISOString({ hours: 14, minutes: 55 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 3,
            lecturer: lecturer.id,
          },
          {
            name: 'Oprogramowanie CMS (Joomla)*',
            form: 'project',
            startTime: createTimeISOString({ hours: 17, minutes: 20 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
        ],
      },
      weekBfullTimeSchedule: {
        monday: [
          {
            name: 'Grafika i komunikacja człowiek-komputer',
            form: 'project',
            startTime: createTimeISOString({ hours: 8, minutes: 0 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 3,
            lecturer: lecturer.id,
          },
          {
            name: 'Ochrona systemów komputerowych przed hakerami i atakami penetracyjnymi*',
            form: 'lab',
            startTime: createTimeISOString({ hours: 12, minutes: 55 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 3,
            lecturer: lecturer.id,
          },
          {
            name: 'Grafika i komunikacja człowiek-komputer',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 15, minutes: 15 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 3,
            lecturer: lecturer.id,
          },
        ],
        tuesday: [
          {
            name: 'Programowanie urządzeń mobilnych',
            form: 'project',
            startTime: createTimeISOString({ hours: 15, minutes: 25 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Systemy operacyjne',
            form: 'project',
            startTime: createTimeISOString({ hours: 17, minutes: 0 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Technologia sieciowa',
            form: 'lab',
            startTime: createTimeISOString({ hours: 18, minutes: 35 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
        ],
        wednesday: [
          {
            name: 'Język angielski',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 9, minutes: 10 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
        ],
        thursday: [
          {
            name: 'Systemy operacyjne',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 9, minutes: 35 }),
            classroom: classroom.id,
            isOnline: true,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Systemy operacyjne',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 11, minutes: 15 }),
            classroom: classroom.id,
            isOnline: true,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Programowanie urządzeń mobilnych ',
            form: 'exercises',
            startTime: createTimeISOString({ hours: 13, minutes: 0 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Programowanie aplikacji WEB',
            form: 'lab',
            startTime: createTimeISOString({ hours: 14, minutes: 40 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Programowanie zaawansowane',
            form: 'project',
            startTime: createTimeISOString({ hours: 16, minutes: 20 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Programowanie zaawansowane',
            form: 'project',
            startTime: createTimeISOString({ hours: 18, minutes: 0 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
        ],
        friday: [
          {
            name: 'Technologia sieciowa',
            form: 'lecture',
            startTime: createTimeISOString({ hours: 8, minutes: 0 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 3,
            lecturer: lecturer.id,
          },
          {
            name: 'Technologia sieciowa',
            form: 'lab',
            startTime: createTimeISOString({ hours: 14, minutes: 30 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
          {
            name: 'Oprogramowanie CMS (Joomla)*',
            form: 'project',
            startTime: createTimeISOString({ hours: 16, minutes: 10 }),
            classroom: classroom.id,
            isOnline: false,
            numberOfHours: 2,
            lecturer: lecturer.id,
          },
        ],
      },
    },
  });

  const courseOfStudy = await payload.create({
    collection: 'coursesOfStudy',
    data: {
      fieldOfStudy: 'Informatyka stosowana',
      faculty: faculty.id,
      schedule: schedule.id,
      courseType: 'fullTime',
      levelOfStudy: 'firstDegree',
      obtainedTitle: 'engineer',
      numberOfSemesters: 7,
      currentSemester: 3,
      startDate: '2023-10-01',
    },
  });

  const profilePicture = await payload.create({
    collection: 'studentProfilePictures',
    data: {},
    filePath: path.resolve(payload.config.custom.dirname, 'assets/jnowak.jpg'),
  });

  await payload.create({
    collection: 'students',
    data: {
      firstName: 'Kamil',
      middleName: 'Jacek',
      familyName: 'Nowak',
      email: 'knowak@ans-ns.edu.pl',
      password: 'demo',
      pesel: '94102087254',
      profilePicture: profilePicture.id,
      coursesOfStudy: [courseOfStudy.id],
    },
  });

  await payload.create({
    collection: 'announcements',
    data: {
      id: 8,
      isBroadcast: true,
      recipients: [],
      subject: 'Ogłoszenie – Zwolnienie z egzaminów!',
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Szanowni Państwo,',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 1,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Z radością ogłaszamy, że w tym semestrze wprowadzamy absolutnie nową, unikalną opcję zwolnienia z egzaminów dla wszystkich studentów! 🎉',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 1,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Na wniosek naszych studentów, postanowiliśmy wprowadzić zwolnienie z egzaminów dla tych, którzy wykażą się niespotykaną kreatywnością. Jak to możliwe? Cóż, w tym roku nie liczymy się już tylko z Twoimi wynikami akademickimi, ale również z Twoimi pomysłami!',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Jak zdobyć zwolnienie?',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 1,
            },
            {
              tag: 'ol',
              type: 'list',
              start: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'listitem',
                  value: 1,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Wyślij filmik, na którym pokazujesz swoją kreatywność w wymyślaniu najnowszego wynalazku, który może zmienić świat (np. zegar na słodycze, samodzielnie czyszczący laptop, czy supernowoczesna wersja kubka do kawy). 🎬',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Filmik musi być zabawny, oryginalny i... niebanalny! Pamiętaj, liczy się pomysłowość.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'listitem',
                  value: 3,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'W tytule maila napisz „Moje zwolnienie z egzaminów – (Twoje imię i nazwisko)”.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
              ],
              listType: 'number',
              direction: 'ltr',
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Wszystkie zgłoszenia prosimy wysyłać na adres: ',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  id: '678d73ef562206308efde35a',
                  type: 'link',
                  fields: {
                    doc: null,
                    url: 'mailto:zwolnienia@ans-ns.edu.pl',
                    newTab: false,
                    linkType: 'custom',
                  },
                  format: '',
                  indent: 0,
                  version: 3,
                  children: [
                    {
                      mode: 'normal',
                      text: 'zwolnienia@ans-ns.edu.pl',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  mode: 'normal',
                  text: '.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Uwaga:',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: ' Liczba zwolnień jest ograniczona, dlatego warto się spieszyć!',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 1,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Ostateczna decyzja komisji zwolnieniowej zostanie ogłoszona po obejrzeniu wszystkich zgłoszeń. Pamiętaj, że im bardziej kreatywnie podejdziesz do zadania, tym większa szansa na sukces! 🚀',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Wszyscy laureaci otrzymają nagrody w postaci zwolnienia z egzaminów, a także fantastycznych gadżetów uczelnianych! 🎁',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Serdecznie zapraszamy do wzięcia udziału w tej wyjątkowej inicjatywie!',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 2,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 2,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Pozdrawiamy,',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Zespół Stypendialny ANS',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
          ],
          direction: 'ltr',
        },
      },
      content_html:
        "<p style='text-align: start;'><strong>Szanowni Państwo,</strong></p><p style='text-align: start;'><strong>Z radością ogłaszamy, że w tym semestrze wprowadzamy absolutnie nową, unikalną opcję zwolnienia z egzaminów dla wszystkich studentów! 🎉</strong></p><p style='text-align: start;'>Na wniosek naszych studentów, postanowiliśmy wprowadzić zwolnienie z egzaminów dla tych, którzy wykażą się niespotykaną kreatywnością. Jak to możliwe? Cóż, w tym roku nie liczymy się już tylko z Twoimi wynikami akademickimi, ale również z Twoimi pomysłami!</p><p style='text-align: start;'><strong>Jak zdobyć zwolnienie?</strong></p><ol class=\"list-number\"><li value=1>Wyślij filmik, na którym pokazujesz swoją kreatywność w wymyślaniu najnowszego wynalazku, który może zmienić świat (np. zegar na słodycze, samodzielnie czyszczący laptop, czy supernowoczesna wersja kubka do kawy). 🎬</li><li value=2>Filmik musi być zabawny, oryginalny i... niebanalny! Pamiętaj, liczy się pomysłowość.</li><li value=3>W tytule maila napisz „Moje zwolnienie z egzaminów – (Twoje imię i nazwisko)”.</li></ol><p style='text-align: start;'>Wszystkie zgłoszenia prosimy wysyłać na adres: <a href=\"mailto:zwolnienia@ans-ns.edu.pl\">zwolnienia@ans-ns.edu.pl</a>.</p><p style='text-align: start;'><strong>Uwaga:</strong> Liczba zwolnień jest ograniczona, dlatego warto się spieszyć!</p><p style='text-align: start;'>Ostateczna decyzja komisji zwolnieniowej zostanie ogłoszona po obejrzeniu wszystkich zgłoszeń. Pamiętaj, że im bardziej kreatywnie podejdziesz do zadania, tym większa szansa na sukces! 🚀</p><p style='text-align: start;'>Wszyscy laureaci otrzymają nagrody w postaci zwolnienia z egzaminów, a także fantastycznych gadżetów uczelnianych! 🎁</p><p style='text-align: start;'><em>Serdecznie zapraszamy do wzięcia udziału w tej wyjątkowej inicjatywie!</em></p><p style='text-align: start;'>Pozdrawiamy,<br>Zespół Stypendialny ANS</p>",
      priority: 'high',
      updatedAt: '2025-01-19T21:52:19.119Z',
      createdAt: '2025-01-19T21:52:19.119Z',
    },
  });

  await payload.create({
    collection: 'announcements',
    data: {
      id: 7,
      isBroadcast: true,
      recipients: [],
      subject: 'Ogłoszenie Biblioteka ANS',
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Szanowni Państwo, Drodzy Studenci,',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'uprzejmie informujemy, że Biblioteka zaprasza codziennie od godz. 8.00 do 18.00, a w soboty od godz. 8.30 do 14.00.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'W tygodniach poprzedzających zimową i letnią sesję egzaminacyjną oraz w czasie sesji godziny dostępności Biblioteki zostaną wydłużone.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Zapraszamy do korzystania z księgozbioru w czytelni z bezpośrednim dostępem do książek. Do dyspozycji pozostaje również czytelnia czasopism i czytelnia komputerowa.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Biblioteka dysponuje dużym księgozbiorem. Posiadamy ponad 100 tysięcy woluminów z wielu różnych dziedzin wiedzy związanych tematyczne z kierunkami nauczania w naszej Uczelni oraz tematami Państwa prac dyplomowych.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Pracownicy Biblioteki chętnie pomagają w wyszukiwaniu literatury na dany temat.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Ponadto jesteśmy otwarci na propozycje studentów dotyczące zakupu nowych pozycji.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Przypominamy też o możliwości zdalnego zamawiania książek przez konto biblioteczne.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Zapraszamy do skorzystania ze szkolenia bibliotecznego (w tym instrukcji zamawiania książek):',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  id: '678d7355562206308efde358',
                  type: 'link',
                  fields: {
                    doc: null,
                    url: 'https://www.ans-ns.edu.pl/uczelnia/biblioteka/szkolenie-biblioteczne',
                    newTab: false,
                    linkType: 'custom',
                  },
                  format: '',
                  indent: 0,
                  version: 3,
                  children: [
                    {
                      mode: 'normal',
                      text: 'https://www.ans-ns.edu.pl/uczelnia/biblioteka/szkolenie-biblioteczne',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Biblioteka przygotowała dostęp do platfomy Ibuk Libra – pierwszej i największej w Polsce czytelni online książek w języku polskim z zakresu humanistyki, nauk społecznych, ekonomicznych, matematyczno-przyrodniczych, prawnych, medycyny i informatyki. W ibuku znajdziecie Państwo elektroniczne wersje czołowych wydawców, m.in. WN PWN, WNT, PZWL, WN Scholar, WKiŁ, OW Impuls, Wolters Kluwer Polska, PWE, GWP.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Aby móc skorzystać z serwisu IBUK LIBRA należy uzyskać specjalny kod dostępu (tzw. PIN). Prośbę o ten kod należy wysyłać pod adres e-mail ',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'autolink',
                  fields: {
                    url: 'mailto:plesniak@ans-ns.edu.pl',
                    linkType: 'custom',
                  },
                  format: '',
                  indent: 0,
                  version: 2,
                  children: [
                    {
                      mode: 'normal',
                      text: 'plesniak@ans-ns.edu.pl',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  mode: 'normal',
                  text: '. ',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: '(UWAGA: studentów prosimy o podawanie w wiadomości swojego numeru albumu).',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 2,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Dostęp do książek znajduje się pod linkiem ',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  id: '678d7355562206308efde359',
                  type: 'link',
                  fields: {
                    doc: null,
                    url: 'https://libra.ibuk.pl/',
                    newTab: false,
                    linkType: 'custom',
                  },
                  format: '',
                  indent: 0,
                  version: 3,
                  children: [
                    {
                      mode: 'normal',
                      text: 'https://libra.ibuk.pl/',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  mode: 'normal',
                  text: '. W pierwszej kolejności rejestrujemy się (podajemy adres e-mail i hasło) i wczytujemy otrzymany kod dostępu. Założenie konta umożliwia użytkownikowi korzystanie z zaawansowanych funkcji do pracy z tekstem.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Zapraszamy do korzystania z pełnotekstowych baz danych. Dostęp z komputerów uczelnianych z poziomu: Biblioteka – zakładka „Bazy danych” – „Wejście do baz EBSCO”.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Istnieje również możliwość korzystania z komputerów domowych, w tym celu należy wysłać prośbę pod adres e-mail ',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'autolink',
                  fields: {
                    url: 'mailto:plesniak@ans-ns.edu.pl',
                    linkType: 'custom',
                  },
                  format: '',
                  indent: 0,
                  version: 2,
                  children: [
                    {
                      mode: 'normal',
                      text: 'plesniak@ans-ns.edu.pl',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  mode: 'normal',
                  text: ' o uzyskanie indywidualnych danych do logowania. Prosimy o podawanie w wiadomości swojego numeru albumu.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Studentów pierwszego roku informujemy, że Biblioteka Główna znajduje się na Al. Wolności 40, a filie biblioteczne w budynkach Wydziału Nauk Społecznych i Sztuki oraz Wydziału Nauk Humanistycznych.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Zapraszamy.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 1,
            },
          ],
          direction: 'ltr',
        },
      },
      content_html:
        '<p><strong>Szanowni Państwo, Drodzy Studenci,</strong><br><br><strong>uprzejmie informujemy, że Biblioteka zaprasza codziennie od godz. 8.00 do 18.00, a w soboty od godz. 8.30 do 14.00.</strong><br><strong>W tygodniach poprzedzających zimową i letnią sesję egzaminacyjną oraz w czasie sesji godziny dostępności Biblioteki zostaną wydłużone.</strong><br><br>Zapraszamy do korzystania z księgozbioru w czytelni z bezpośrednim dostępem do książek. Do dyspozycji pozostaje również czytelnia czasopism i czytelnia komputerowa.<br>Biblioteka dysponuje dużym księgozbiorem. Posiadamy ponad 100 tysięcy woluminów z wielu różnych dziedzin wiedzy związanych tematyczne z kierunkami nauczania w naszej Uczelni oraz tematami Państwa prac dyplomowych.<br>Pracownicy Biblioteki chętnie pomagają w wyszukiwaniu literatury na dany temat.<br>Ponadto jesteśmy otwarci na propozycje studentów dotyczące zakupu nowych pozycji.<br>Przypominamy też o możliwości zdalnego zamawiania książek przez konto biblioteczne.<br><br>Zapraszamy do skorzystania ze szkolenia bibliotecznego (w tym instrukcji zamawiania książek):<br><a href="https://www.ans-ns.edu.pl/uczelnia/biblioteka/szkolenie-biblioteczne">https://www.ans-ns.edu.pl/uczelnia/biblioteka/szkolenie-biblioteczne</a><br><br>Biblioteka przygotowała dostęp do platfomy Ibuk Libra – pierwszej i największej w Polsce czytelni online książek w języku polskim z zakresu humanistyki, nauk społecznych, ekonomicznych, matematyczno-przyrodniczych, prawnych, medycyny i informatyki. W ibuku znajdziecie Państwo elektroniczne wersje czołowych wydawców, m.in. WN PWN, WNT, PZWL, WN Scholar, WKiŁ, OW Impuls, Wolters Kluwer Polska, PWE, GWP.<br><br>Aby móc skorzystać z serwisu IBUK LIBRA należy uzyskać specjalny kod dostępu (tzw. PIN). Prośbę o ten kod należy wysyłać pod adres e-mail <a href="mailto:plesniak@ans-ns.edu.pl">plesniak@ans-ns.edu.pl</a>. <em>(UWAGA: studentów prosimy o podawanie w wiadomości swojego numeru albumu).</em><br><br>Dostęp do książek znajduje się pod linkiem <a href="https://libra.ibuk.pl/">https://libra.ibuk.pl/</a>. W pierwszej kolejności rejestrujemy się (podajemy adres e-mail i hasło) i wczytujemy otrzymany kod dostępu. Założenie konta umożliwia użytkownikowi korzystanie z zaawansowanych funkcji do pracy z tekstem.<br><br>Zapraszamy do korzystania z pełnotekstowych baz danych. Dostęp z komputerów uczelnianych z poziomu: Biblioteka – zakładka „Bazy danych” – „Wejście do baz EBSCO”.<br><br>Istnieje również możliwość korzystania z komputerów domowych, w tym celu należy wysłać prośbę pod adres e-mail <a href="mailto:plesniak@ans-ns.edu.pl">plesniak@ans-ns.edu.pl</a> o uzyskanie indywidualnych danych do logowania. Prosimy o podawanie w wiadomości swojego numeru albumu.<br><br><strong>Studentów pierwszego roku informujemy, że Biblioteka Główna znajduje się na Al. Wolności 40, a filie biblioteczne w budynkach Wydziału Nauk Społecznych i Sztuki oraz Wydziału Nauk Humanistycznych.</strong><br><br><strong>Zapraszamy.</strong></p>',
      priority: 'low',
      updatedAt: '2025-01-19T21:49:11.745Z',
      createdAt: '2025-01-19T21:49:11.745Z',
    },
  });

  await payload.create({
    collection: 'announcements',
    data: {
      id: 6,
      isBroadcast: true,
      recipients: [],
      subject: 'Stypendium dla każdego!',
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Szanowni Państwo,',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 1,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'W związku z Dniem Studenta oraz przypadającą w tym roku wyjątkową datą – 19.01.2025 – z radością informujemy, że każdy student naszej uczelni może otrzymać darmowe stypendium specjalne! Jednak tym razem nie będzie to zależne od ocen czy osiągnięć naukowych, ale od... liczby posiadanych psów! 🐶',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 1,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Anektujemy z życia uczelni historię, kiedy to pewien student, próbując zaimponować swojej grupie projektowej, opowiadał, że ma aż 10 psów – każdy z nich z imieniem związanym z literaturą polską! I choć wówczas nie przewidział, że uczelnia wprowadzi takie stypendium, dzisiaj może być absolutnym zwycięzcą! 😄',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Nie masz psa? Bez obaw! Możesz przyprowadzić zaprzyjaźnionego czworonoga na uczelnię, a komisja z pewnością doceni Twoje zaangażowanie. Bonusowe punkty za kreatywne imiona psów! 🎓',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Jak ubiegać się o stypendium?',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 1,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              tag: 'ul',
              type: 'list',
              start: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'listitem',
                  value: 1,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Prześlij zdjęcie swojego psa na adres: ',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                    {
                      id: '678d7317562206308efde356',
                      type: 'link',
                      fields: {
                        doc: null,
                        url: 'mailto:stypendia@ans-ns.edu.pl',
                        newTab: false,
                        linkType: 'custom',
                      },
                      format: '',
                      indent: 0,
                      version: 3,
                      children: [
                        {
                          mode: 'normal',
                          text: 'stypendia@ans-ns.edu.pl',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      mode: 'normal',
                      text: '.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'W temacie wiadomości wpisz „Mój pies i ja”.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'listitem',
                  value: 3,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Opisz w kilku zdaniach, dlaczego Twój pies zasługuje na stypendium.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
              ],
              listType: 'bullet',
              direction: 'ltr',
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Regulamin akcji dostępny jest na stronie: ',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  id: '678d7317562206308efde357',
                  type: 'link',
                  fields: {
                    doc: null,
                    url: 'https://www.ans-ns.edu.pl/stypendia',
                    newTab: false,
                    linkType: 'custom',
                  },
                  format: '',
                  indent: 0,
                  version: 3,
                  children: [
                    {
                      mode: 'normal',
                      text: 'https://www.ans-ns.edu.pl/stypendia',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  mode: 'normal',
                  text: '.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Zapraszamy do wspólnej zabawy i korzystania z tej nietypowej okazji!',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 2,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Serdecznie pozdrawiamy,',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'linebreak',
                  version: 1,
                },
                {
                  mode: 'normal',
                  text: 'Zespół Stypendialny ANS',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
          ],
          direction: 'ltr',
        },
      },
      content_html:
        "<p style='text-align: start;'><strong>Szanowni Państwo,</strong></p><p style='text-align: start;'><strong>W związku z Dniem Studenta oraz przypadającą w tym roku wyjątkową datą – 19.01.2025 – z radością informujemy, że każdy student naszej uczelni może otrzymać darmowe stypendium specjalne! Jednak tym razem nie będzie to zależne od ocen czy osiągnięć naukowych, ale od... liczby posiadanych psów! 🐶</strong></p><p style='text-align: start;'>Anektujemy z życia uczelni historię, kiedy to pewien student, próbując zaimponować swojej grupie projektowej, opowiadał, że ma aż 10 psów – każdy z nich z imieniem związanym z literaturą polską! I choć wówczas nie przewidział, że uczelnia wprowadzi takie stypendium, dzisiaj może być absolutnym zwycięzcą! 😄</p><p style='text-align: start;'>Nie masz psa? Bez obaw! Możesz przyprowadzić zaprzyjaźnionego czworonoga na uczelnię, a komisja z pewnością doceni Twoje zaangażowanie. Bonusowe punkty za kreatywne imiona psów! 🎓</p><p style='text-align: start;'><strong>Jak ubiegać się o stypendium?</strong></p><ul class=\"list-bullet\"><li value=1>Prześlij zdjęcie swojego psa na adres: <a href=\"mailto:stypendia@ans-ns.edu.pl\">stypendia@ans-ns.edu.pl</a>.</li><li value=2>W temacie wiadomości wpisz „Mój pies i ja”.</li><li value=3>Opisz w kilku zdaniach, dlaczego Twój pies zasługuje na stypendium.</li></ul><p style='text-align: start;'>Regulamin akcji dostępny jest na stronie: <a href=\"https://www.ans-ns.edu.pl/stypendia\">https://www.ans-ns.edu.pl/stypendia</a>.</p><p style='text-align: start;'><em>Zapraszamy do wspólnej zabawy i korzystania z tej nietypowej okazji!</em></p><p style='text-align: start;'>Serdecznie pozdrawiamy,<br>Zespół Stypendialny ANS</p>",
      priority: 'high',
      updatedAt: '2025-01-19T21:49:18.648Z',
      createdAt: '2025-01-19T21:42:44.456Z',
    },
  });

  await payload.create({
    collection: 'announcements',
    data: {
      id: 5,
      isBroadcast: true,
      recipients: [],
      subject: 'Harmonogram egzaminów zimowych',
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Uprzejmie informujemy, że egzaminy zimowe odbędą się w trybie online zgodnie z poniższym harmonogramem:',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
            {
              tag: 'ul',
              type: 'list',
              start: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'listitem',
                  value: 1,
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Matematyka - 10 stycznia, godz. 10:00',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Fizyka - 12 stycznia, godz. 12:00',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  type: 'listitem',
                  value: 3,
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Informatyka - 15 stycznia, godz. 14:00',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
              ],
              listType: 'bullet',
              direction: 'ltr',
            },
            {
              type: 'paragraph',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Prosimy o wcześniejsze zapoznanie się z regulaminem egzaminów online dostępnym pod adresem ',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
                {
                  type: 'autolink',
                  fields: {
                    url: 'https://example.com/',
                    linkType: 'custom',
                  },
                  format: '',
                  indent: 0,
                  version: 2,
                  children: [
                    {
                      mode: 'normal',
                      text: 'https://example.com/',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                },
                {
                  mode: 'normal',
                  text: '.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              textStyle: '',
              textFormat: 0,
            },
          ],
          direction: 'ltr',
        },
      },
      content_html:
        '<p>Uprzejmie informujemy, że egzaminy zimowe odbędą się w trybie online zgodnie z poniższym harmonogramem:</p><ul class="list-bullet"><li value=1>Matematyka - 10 stycznia, godz. 10:00</li><li value=2>Fizyka - 12 stycznia, godz. 12:00</li><li value=3>Informatyka - 15 stycznia, godz. 14:00</li></ul><p>Prosimy o wcześniejsze zapoznanie się z regulaminem egzaminów online dostępnym pod adresem <a href="https://example.com/">https://example.com/</a>.</p>',
      priority: 'high',
      updatedAt: '2025-01-19T21:40:24.381Z',
      createdAt: '2025-01-19T21:40:24.381Z',
    },
  });
}
