/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    pages: Page;
    products: Product;
    images: Image;
    videos: Video;
    'case-studies': CaseStudy;
    'case-studies-categories': CaseStudiesCategory;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    header: Header;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  stripeID?: string | null;
  skipSync?: boolean | null;
  name?: string | null;
  roles?: ('admin' | 'user')[] | null;
  subscriptions?:
    | {
        stripeID?: string | null;
        product?: (number | null) | Product;
        status?:
          | ('active' | 'canceled' | 'incomplete' | 'incomplete_expired' | 'past_due' | 'trialing' | 'unpaid')
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  stripeID?: string | null;
  skipSync?: boolean | null;
  prices?:
    | {
        name: string;
        stripeID?: string | null;
        price: number;
        paymentType: 'one_time' | 'recurring';
        subscriptionIntervalType?: ('day' | 'week' | 'month' | 'year') | null;
        subscriptionIntervalCount?: number | null;
        trialPeriodDays?: number | null;
        marketingNote?: string | null;
        qualities?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content?:
    | (
        | {
            title: string;
            text?: string | null;
            image: number | Image;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeHero';
          }
        | {
            label?: string | null;
            title: string;
            image?: number | Image | null;
            description?: string | null;
            transparentSidePanel?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baseHero';
          }
        | {
            title: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productsList';
          }
        | {
            title: string;
            image: number | Image;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baseImageTitle';
          }
        | {
            label: string;
            steps?:
              | {
                  title: string;
                  qualities: {
                    text: string;
                    id?: string | null;
                  }[];
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baseSteps';
          }
        | {
            wysiwyg: {
              [k: string]: unknown;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'baseWysiwyg';
          }
        | {
            hasAll?: boolean | null;
            relatedCases?: (number | CaseStudy)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudiesList';
          }
        | {
            title: string;
            info?:
              | {
                  infoTitle: string;
                  infoContent: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'titleInfo';
          }
        | {
            image: number | Image;
            title: string;
            benefits?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefitsList';
          }
        | {
            title: string;
            text?: string | null;
            items?:
              | {
                  title: string;
                  qualities?:
                    | {
                        text?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'verticalList';
          }
        | {
            title: string;
            items?:
              | {
                  backgroundType: 'solid' | 'image';
                  theme: 'dark' | 'light';
                  height?: ('1/3' | '2/3' | '3/3') | null;
                  image?: number | Image | null;
                  title: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'flexibleGrid';
          }
        | {
            title: string;
            text?: string | null;
            image?: number | Image | null;
            items?:
              | {
                  title?: string | null;
                  text: string;
                  solidBackground?: boolean | null;
                  indent?: boolean | null;
                  includeOrderNumber?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baseStairs';
          }
        | {
            label: string;
            video: number | Video;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baseVideo';
          }
        | {
            label: string;
            brands?:
              | {
                  brand: number | Image;
                  height: number;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'brandsSlider';
          }
      )[]
    | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  category?: (number | null) | CaseStudiesCategory;
  image: number | Image;
  excerpt: string;
  content?:
    | (
        | {
            label?: string | null;
            title: string;
            image?: number | Image | null;
            description?: string | null;
            transparentSidePanel?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baseHero';
          }
        | {
            title: string;
            image: number | Image;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baseImageTitle';
          }
        | {
            label: string;
            steps?:
              | {
                  title: string;
                  qualities: {
                    text: string;
                    id?: string | null;
                  }[];
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'baseSteps';
          }
        | {
            hasAll?: boolean | null;
            relatedCases?: (number | CaseStudy)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudiesList';
          }
        | {
            title: string;
            info?:
              | {
                  infoTitle: string;
                  infoContent: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'titleInfo';
          }
        | {
            label: string;
            title: string;
            mainText: string;
            secondaryText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'labelTitleContent';
          }
        | {
            image: number | Image;
            title: string;
            benefits?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefitsList';
          }
      )[]
    | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-categories".
 */
export interface CaseStudiesCategory {
  id: number;
  name: string;
  slug?: string | null;
  caseStudies?: (number | CaseStudy)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  links?:
    | {
        type?: ('simple' | 'dropdown') | null;
        label: string;
        simpleLink?: (number | null) | Page;
        dropdownLinks?:
          | {
              label: string;
              link: number | Page;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}