name: Staging build and deployment

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: karpiel-department
    environment:
      name: staging
      url: https://cms.easyfiscal.karpiel-department.pl
    env:
      DATABASE_URI: ${{secrets.DATABASE_URI}}
      PAYLOAD_SECRET: ${{secrets.PAYLOAD_SECRET}}
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Archive build artifacts
        run: tar -czvf build.tar.gz .

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}

      - name: Prepare deployment dir
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOYMENT_USERNAME }}@easyfiscal.karpiel-department.pl "
            mkdir -p /home/${{secrets.DEPLOYMENT_USERNAME}}/easyfiscal-cms-staging
          "

      - name: Transfer build artifacts
        run: scp -o StrictHostKeyChecking=no build.tar.gz ${{ secrets.DEPLOYMENT_USERNAME }}@easyfiscal.karpiel-department.pl:/home/${{secrets.DEPLOYMENT_USERNAME}}/easyfiscal-cms-staging

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOYMENT_USERNAME }}@easyfiscal.karpiel-department.pl "
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            # npm install pm2@latest -g
            # pm2 update
            cd /home/${{secrets.DEPLOYMENT_USERNAME}}/easyfiscal-cms-staging
            rm -r ./.output ./ecosystem.config.js
            tar -xzvf build.tar.gz
            pm2 stop ecosystem.config.js
            rm -r ./.prod
            mkdir ./.prod
            cp -r ./.output/* ./.prod
            pm2 start ecosystem.config.js
            sleep 2
            curl -f --silent --show-error localhost:4100 1>/dev/null && echo success
          "
